vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '/upload/images'
            upload_destination: '%kernel.project_dir%/public/upload/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false